### ISSUE TITLE
Added already complete deficiency course

### ISSUE THREAD

**Issue by sachingrover211** [yochan-lab/iPass-MasterPlan#1]
Validate returns bad operator and we show So far so good in the UI. There should be some error shown saying that some rules are not met or something.

**Comment by AdityaPrasadMishra** [comment]
Also when selecting the already completed deficiency course we see that the IPOS becomes valid. Please see the attached picture below.
![haaibug0101](https://user-images.githubusercontent.com/13311691/45002623-9cc1db80-af8d-11e8-9f21-af0138524dec.png)

**Comment by sailik1991** [comment]
See this: https://github.com/yochan-lab/iPass-MasterPlan/issues/7
