### ISSUE TITLE
 Inconsistency in the way the initial screen comes up. 

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#2]
Description -> 
When the screen loads for an user A in fig a  we can see that there are no actions cum steps in IPOS which is correct. But when the 2nd user comes we can see he is shown with the IPOS steps which the user 1 left the screen (refer to fig b). The steps remain even after we restart the server from command line. 

Pictures ->
![getimage](https://user-images.githubusercontent.com/13311691/45002431-52d7f600-af8b-11e8-9534-a6bf7ac11664.png)
![getimage 1](https://user-images.githubusercontent.com/13311691/45002432-52d7f600-af8b-11e8-89a3-c2f28457d0c4.png)

Priority -> C 

Expected solution -> 

For each user either the Screen should start with no actions in IPOS or should have some basic set of sections which is consistent across users.

**Comment by sachingrover211** [comment]
https://github.com/yochan-lab/iPass-MasterPlan/commit/ab676a1c3e9bc3eaefc117871602a13df9933464

@AdityaPrasadMishra verify the bug now.

**Comment by AdityaPrasadMishra** [comment]
Issue is fixed now as I could see a screen with no actions on IPOS.
