### ISSUE TITLE
User Experience Issue with the non-removing error messages

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#3]
## Description ->
From the attached figure you can clearly see that the message "This is not a Valid iPOS! Try again" do not disappear even after user corrected his mistakes. 

## Pictures ->
![bug0201](https://user-images.githubusercontent.com/13311691/45002474-bbbf6e00-af8b-11e8-9acc-f7fffd311704.png)

## Possible Solution -> 
The old error message should not be present as error is rectified.

**Comment by sachingrover211** [comment]
@AdityaPrasadMishra this one is also fixed.

https://github.com/yochan-lab/iPass-MasterPlan/commit/7eeb6bda93cac7fbfaa001a5dd3723ff7040edb8

Please check this one.

**Comment by AdityaPrasadMishra** [comment]
Closing this issue as it was fixed. Verified it as well.
