### ISSUE TITLE
No option to select international Student from UI

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#4]
# Description ->
This could be as design. but still putting it out here. There is no option to select whether someone is international student or not.

# Pictures ->
![bug0301](https://user-images.githubusercontent.com/13311691/45002584-0db4c380-af8d-11e8-8933-677b5958543d.png)

# Priority -> C

# Expected Solution -> 
Some kind of feature to select if someone is an international student or not.

**Comment by sachingrover211** [comment]
This is design.
