### ISSUE TITLE
Check Button is not working as expected

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#5]
## Description -> 
Check button is not working as expected. Following scenarios are the scenarios where it is not working as expected.
*  We are able to submit an IPOS with Deficiencies.
![bug0501](https://user-images.githubusercontent.com/13311691/45002800-95033680-af8f-11e8-8128-2ac9a3174b0f.png)
*  We are able to defend without selecting the chair and committee member.
![bug0502](https://user-images.githubusercontent.com/13311691/45002801-95033680-af8f-11e8-8629-b282ddbd11f7.png)
*  Even when specialization is selected we see that the chair could be from different specialization.
![bug0503](https://user-images.githubusercontent.com/13311691/45002802-95033680-af8f-11e8-8b54-cf8fd260703c.png)
*  Without selecting mandatory courses for Specialization we are able to submit the IPOS.
![bug0503](https://user-images.githubusercontent.com/13311691/45002802-95033680-af8f-11e8-8b54-cf8fd260703c.png)
*  Without completing required foundation,system and application course the IPOS was accepted.
![bug0504](https://user-images.githubusercontent.com/13311691/45002803-95033680-af8f-11e8-81c0-6177f4541c74.png)

Attaching one picture for each of the scenario.

# Priority -> A  

# Expected Solution ->
 Check button functionality must be tested properly after fixing the issues mentioned above.

**Comment by sailik1991** [comment]
I have pushed in the code to handle this. Can you verify and revert back on the thread?

**Comment by sachingrover211** [comment]
Code is in this commit https://github.com/yochan-lab/iPass-MasterPlan/commit/7eeb6bda93cac7fbfaa001a5dd3723ff7040edb8

**Comment by AdityaPrasadMishra** [comment]
Check button is working fine now and IPOS is getting submitted only when it is valid
