### ISSUE TITLE
Validate button is saying that the IPOS is invalid but check button still accepts it

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#6]
# Description ->
 When the validate button itself is stating that the IPOS is invalid, the check button is still passing the iPOS. Please see the attached pics.
![bug0601](https://user-images.githubusercontent.com/13311691/45002871-81a49b00-af90-11e8-9826-1d62060a3def.png)
![bug0504](https://user-images.githubusercontent.com/13311691/45002874-85382200-af90-11e8-8dbb-87a29150c849.png)

# Priority -> A

# Expected Solution -> 
Validate and check button should be in sync.

**Comment by sailik1991** [comment]
I have checked in the code to handle this as well. Can you please verify and revert back on the thread.

**Comment by sachingrover211** [comment]
Fixed with Issue #5

**Comment by AdityaPrasadMishra** [comment]
Issue is fixed with issue number 5.
