### ISSUE TITLE
The IPOS plan rearranges upon adding a new action

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#9]
## Description -> 
Upon adding a new action in the IPOS the Steps IPOS rearranges and disturbs the order of the plan.

## Pictures ->
![bug0901](https://user-images.githubusercontent.com/13311691/45009548-8e8bb380-afbd-11e8-9b1c-06ca8fecca34.png)
![bug0902](https://user-images.githubusercontent.com/13311691/45009549-8e8bb380-afbd-11e8-9519-e95484d59f5d.png)

## Expected Resolution ->
No rearrangement should happen.

**Comment by sailik1991** [comment]
Please verify.

**Comment by AdityaPrasadMishra** [comment]
Verified it and it is fixed
